// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjZ9gSvcvgRT59EaWs5oQhlknoP03bfVc',
    appId: '1:599855476302:web:80167a5617561300891d1f',
    messagingSenderId: '599855476302',
    projectId: 'testfirebse-213fe',
    authDomain: 'testfirebse-213fe.firebaseapp.com',
    storageBucket: 'testfirebse-213fe.appspot.com',
    measurementId: 'G-R6GWX3J998',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3emI6qEke-XCIJ1bHfwOFRA3gfcTbE7w',
    appId: '1:599855476302:android:e6f3688d3c4ec1ff891d1f',
    messagingSenderId: '599855476302',
    projectId: 'testfirebse-213fe',
    storageBucket: 'testfirebse-213fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW5Bw77kv0sVdNU7TbaVlq4AZOP0mRH3k',
    appId: '1:599855476302:ios:a7434f0c604baffa891d1f',
    messagingSenderId: '599855476302',
    projectId: 'testfirebse-213fe',
    storageBucket: 'testfirebse-213fe.appspot.com',
    iosBundleId: 'com.example.testFirebase',
  );
}
